// Auto-generated by scripts/build-embed.js
// Full Tier X + XI list with Nation/Class (offline)
window.EMBEDDED_SHIPS = [
  {
    "name": "Admiral Nakhimov",
    "tier": 10,
    "nation": "USSR",
    "class": "Carrier"
  },
  {
    "name": "Admiral Ushakov",
    "tier": 11,
    "nation": "USSR",
    "class": "Battleship"
  },
  {
    "name": "Alexander Nevsky",
    "tier": 10,
    "nation": "USSR",
    "class": "Cruiser"
  },
  {
    "name": "Álvaro de Bazán",
    "tier": 10,
    "nation": "Spain",
    "class": "Destroyer"
  },
  {
    "name": "Annapolis",
    "tier": 11,
    "nation": "USA",
    "class": "Cruiser"
  },
  {
    "name": "ARP Yamato",
    "tier": 10,
    "nation": "Japan",
    "class": "Battleship"
  },
  {
    "name": "Attilio Regolo",
    "tier": 10,
    "nation": "Italy",
    "class": "Destroyer"
  },
  {
    "name": "Audacious",
    "tier": 10,
    "nation": "UK",
    "class": "Carrier"
  },
  {
    "name": "Austin",
    "tier": 10,
    "nation": "USA",
    "class": "Cruiser"
  },
  {
    "name": "Balao",
    "tier": 10,
    "nation": "USA",
    "class": "Submarine"
  },
  {
    "name": "Bourgogne",
    "tier": 10,
    "nation": "France",
    "class": "Battleship"
  },
  {
    "name": "Clausewitz",
    "tier": 11,
    "nation": "Germany",
    "class": "Cruiser"
  },
  {
    "name": "Colbert",
    "tier": 10,
    "nation": "France",
    "class": "Cruiser"
  },
  {
    "name": "Condé",
    "tier": 11,
    "nation": "France",
    "class": "Cruiser"
  },
  {
    "name": "Conqueror",
    "tier": 10,
    "nation": "UK",
    "class": "Battleship"
  },
  {
    "name": "Cristoforo Colombo",
    "tier": 10,
    "nation": "Italy",
    "class": "Battleship"
  },
  {
    "name": "Dalarna",
    "tier": 11,
    "nation": "Europe",
    "class": "Destroyer"
  },
  {
    "name": "Daring",
    "tier": 10,
    "nation": "UK",
    "class": "Destroyer"
  },
  {
    "name": "Delny",
    "tier": 10,
    "nation": "USSR",
    "class": "Destroyer"
  },
  {
    "name": "Des Moines",
    "tier": 10,
    "nation": "USA",
    "class": "Cruiser"
  },
  {
    "name": "Druid",
    "tier": 10,
    "nation": "UK",
    "class": "Destroyer"
  },
  {
    "name": "Eagle",
    "tier": 11,
    "nation": "UK",
    "class": "Carrier"
  },
  {
    "name": "Edgar",
    "tier": 11,
    "nation": "UK",
    "class": "Cruiser"
  },
  {
    "name": "Elbing",
    "tier": 10,
    "nation": "Germany",
    "class": "Destroyer"
  },
  {
    "name": "Forrest Sherman",
    "tier": 10,
    "nation": "USA",
    "class": "Destroyer"
  },
  {
    "name": "Franklin D. Roosevelt",
    "tier": 10,
    "nation": "USA",
    "class": "Carrier"
  },
  {
    "name": "Gearing",
    "tier": 10,
    "nation": "USA",
    "class": "Destroyer"
  },
  {
    "name": "Gibraltar",
    "tier": 10,
    "nation": "UK",
    "class": "Cruiser"
  },
  {
    "name": "Goliath",
    "tier": 10,
    "nation": "UK",
    "class": "Cruiser"
  },
  {
    "name": "Gouden Leeuw",
    "tier": 10,
    "nation": "Netherlands",
    "class": "Cruiser"
  },
  {
    "name": "Grosser Kurfürst",
    "tier": 10,
    "nation": "Germany",
    "class": "Battleship"
  },
  {
    "name": "Grozovoi",
    "tier": 10,
    "nation": "USSR",
    "class": "Destroyer"
  },
  {
    "name": "Hakuryū",
    "tier": 10,
    "nation": "Japan",
    "class": "Carrier"
  },
  {
    "name": "Halland",
    "tier": 10,
    "nation": "Europe",
    "class": "Destroyer"
  },
  {
    "name": "Hannover",
    "tier": 11,
    "nation": "Germany",
    "class": "Battleship"
  },
  {
    "name": "Harugumo",
    "tier": 10,
    "nation": "Japan",
    "class": "Destroyer"
  },
  {
    "name": "Hayate",
    "tier": 10,
    "nation": "Japan",
    "class": "Destroyer"
  },
  {
    "name": "Henri IV",
    "tier": 10,
    "nation": "France",
    "class": "Cruiser"
  },
  {
    "name": "Hindenburg",
    "tier": 10,
    "nation": "Germany",
    "class": "Cruiser"
  },
  {
    "name": "Incomparable",
    "tier": 10,
    "nation": "UK",
    "class": "Battleship"
  },
  {
    "name": "Jinan",
    "tier": 10,
    "nation": "Pan-Asia",
    "class": "Cruiser"
  },
  {
    "name": "Khabarovsk",
    "tier": 10,
    "nation": "USSR",
    "class": "Destroyer"
  },
  {
    "name": "Kléber",
    "tier": 10,
    "nation": "France",
    "class": "Destroyer"
  },
  {
    "name": "Kremlin",
    "tier": 10,
    "nation": "USSR",
    "class": "Battleship"
  },
  {
    "name": "Louisiana",
    "tier": 10,
    "nation": "USA",
    "class": "Battleship"
  },
  {
    "name": "Malta",
    "tier": 10,
    "nation": "UK",
    "class": "Carrier"
  },
  {
    "name": "Manfred von Richthofen",
    "tier": 10,
    "nation": "Germany",
    "class": "Carrier"
  },
  {
    "name": "Marceau",
    "tier": 10,
    "nation": "France",
    "class": "Destroyer"
  },
  {
    "name": "Marseille",
    "tier": 10,
    "nation": "France",
    "class": "Cruiser"
  },
  {
    "name": "Max Immelmann",
    "tier": 10,
    "nation": "Germany",
    "class": "Carrier"
  },
  {
    "name": "Mecklenburg",
    "tier": 10,
    "nation": "Germany",
    "class": "Battleship"
  },
  {
    "name": "Midway",
    "tier": 10,
    "nation": "USA",
    "class": "Carrier"
  },
  {
    "name": "Minotaur",
    "tier": 10,
    "nation": "UK",
    "class": "Cruiser"
  },
  {
    "name": "Montana",
    "tier": 10,
    "nation": "USA",
    "class": "Battleship"
  },
  {
    "name": "Moskva",
    "tier": 10,
    "nation": "USSR",
    "class": "Cruiser"
  },
  {
    "name": "Napoli",
    "tier": 10,
    "nation": "Italy",
    "class": "Cruiser"
  },
  {
    "name": "Ohio",
    "tier": 10,
    "nation": "USA",
    "class": "Battleship"
  },
  {
    "name": "Patrie",
    "tier": 11,
    "nation": "France",
    "class": "Battleship"
  },
  {
    "name": "Petropavlovsk",
    "tier": 10,
    "nation": "USSR",
    "class": "Cruiser"
  },
  {
    "name": "Plymouth",
    "tier": 10,
    "nation": "UK",
    "class": "Cruiser"
  },
  {
    "name": "Preussen",
    "tier": 10,
    "nation": "Germany",
    "class": "Battleship"
  },
  {
    "name": "Puerto Rico",
    "tier": 10,
    "nation": "USA",
    "class": "Cruiser"
  },
  {
    "name": "Ragnar",
    "tier": 10,
    "nation": "Europe",
    "class": "Destroyer"
  },
  {
    "name": "République",
    "tier": 10,
    "nation": "France",
    "class": "Battleship"
  },
  {
    "name": "Salem",
    "tier": 10,
    "nation": "USA",
    "class": "Cruiser"
  },
  {
    "name": "Satsuma",
    "tier": 11,
    "nation": "Japan",
    "class": "Battleship"
  },
  {
    "name": "Schlieffen",
    "tier": 10,
    "nation": "Germany",
    "class": "Battleship"
  },
  {
    "name": "Sekiryu",
    "tier": 11,
    "nation": "Japan",
    "class": "Carrier"
  },
  {
    "name": "Sevastopol",
    "tier": 10,
    "nation": "USSR",
    "class": "Cruiser"
  },
  {
    "name": "Shikishima",
    "tier": 10,
    "nation": "Japan",
    "class": "Battleship"
  },
  {
    "name": "Shimakaze",
    "tier": 10,
    "nation": "Japan",
    "class": "Destroyer"
  },
  {
    "name": "Slava",
    "tier": 10,
    "nation": "USSR",
    "class": "Battleship"
  },
  {
    "name": "Småland",
    "tier": 10,
    "nation": "Europe",
    "class": "Destroyer"
  },
  {
    "name": "Smolensk",
    "tier": 10,
    "nation": "USSR",
    "class": "Cruiser"
  },
  {
    "name": "Somers",
    "tier": 10,
    "nation": "USA",
    "class": "Destroyer"
  },
  {
    "name": "St. Vincent",
    "tier": 10,
    "nation": "UK",
    "class": "Battleship"
  },
  {
    "name": "Stalingrad",
    "tier": 10,
    "nation": "USSR",
    "class": "Cruiser"
  },
  {
    "name": "Thrasher",
    "tier": 10,
    "nation": "UK",
    "class": "Submarine"
  },
  {
    "name": "Thunderer",
    "tier": 10,
    "nation": "UK",
    "class": "Battleship"
  },
  {
    "name": "Tromp",
    "tier": 10,
    "nation": "Netherlands",
    "class": "Destroyer"
  },
  {
    "name": "U-2501",
    "tier": 10,
    "nation": "Germany",
    "class": "Submarine"
  },
  {
    "name": "United States",
    "tier": 11,
    "nation": "USA",
    "class": "Carrier"
  },
  {
    "name": "Vampire II",
    "tier": 10,
    "nation": "Commonwealth",
    "class": "Destroyer"
  },
  {
    "name": "Venezia",
    "tier": 10,
    "nation": "Italy",
    "class": "Cruiser"
  },
  {
    "name": "Vermont",
    "tier": 10,
    "nation": "USA",
    "class": "Battleship"
  },
  {
    "name": "Worcester",
    "tier": 10,
    "nation": "USA",
    "class": "Cruiser"
  },
  {
    "name": "Yamagiri",
    "tier": 11,
    "nation": "Japan",
    "class": "Destroyer"
  },
  {
    "name": "Yamato",
    "tier": 10,
    "nation": "Japan",
    "class": "Battleship"
  },
  {
    "name": "Yodo",
    "tier": 10,
    "nation": "Japan",
    "class": "Cruiser"
  },
  {
    "name": "Yoshino",
    "tier": 10,
    "nation": "Japan",
    "class": "Cruiser"
  },
  {
    "name": "Yoshino B",
    "tier": 10,
    "nation": "Japan",
    "class": "Cruiser"
  },
  {
    "name": "Yueyang",
    "tier": 10,
    "nation": "Pan-Asia",
    "class": "Destroyer"
  },
  {
    "name": "Z-42",
    "tier": 10,
    "nation": "Germany",
    "class": "Destroyer"
  },
  {
    "name": "Georg Hoffmann",
    "tier": 10,
    "nation": "Germany",
    "class": "Destroyer"
  },
  {
    "name": "Z-52",
    "tier": 10,
    "nation": "Germany",
    "class": "Destroyer"
  },
  {
    "name": "Zaō",
    "tier": 10,
    "nation": "Japan",
    "class": "Cruiser"
  },
  {
    "name": "Zorkiy",
    "tier": 11,
    "nation": "USSR",
    "class": "Destroyer"
  }
];
